### PR TITLE
Added merged MagField interpolation files to grid_160812_3_8t

### PR DESCRIPTION
**Pull request by Dr15Jones**
These are more efficient to read than the individual files.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This is the follow up to cms-sw/cmssw#38051

**Comment by Dr15Jones** [comment]
@namapane FYI

**Comment by namapane** [comment]
> @namapane FYI

Thank you Christ for taking care of this. Was in my list but did not find time to have a look in the meanwhile...

**Comment by clacaputo** [comment]
Hi @Dr15Jones , I don't remember whether these files are declared already as input after https://github.com/cms-sw/cmssw/pull/38051. If this is the case, it should be possible to use them triggering the test here, right?

**Comment by Dr15Jones** [comment]
@smuzaffar what is the procedure for testing this kind of PR?

**Comment by namapane** [comment]
As far as I understand as soon as these externals are added, the new files will be found and picked up automatically. The normal unit tests in MagneticField would spot any issue.

**Comment by smuzaffar** [comment]
@namapane ,is there any unit test which uses these new files?

**Comment by namapane** [comment]
> @namapane ,is there any unit test which uses these new files?

Yes, the standard MF unit tests:
https://github.com/cms-sw/cmssw/blob/master/MagneticField/Engine/test/runTest.sh

since #38051is designed to have merged files picked up if available by default (cf 
https://github.com/Dr15Jones/cmssw/blob/master/MagneticField/GeomBuilder/plugins/dd4hep/DD4hep_VolumeBasedMagneticFieldESProducer.cc#L116 ) instead of the individual files.

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = MagneticField/Engine

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals
looks good, the DQM/Reco comparison diferencs are in MessageLogger

**Comment by clacaputo** [comment]
+reconstruction

**Comment by Dr15Jones** [comment]
What is the time scale for getting this merged?

**Comment by perrotta** [comment]
> What is the time scale for getting this merged?

Basically now... 
Indeed cms-data updates not linked to any particular CMSSW PR can easily get out of sight: you did well in reminding us about it

**Comment by perrotta** [comment]
+1

**Pull request merged**
