### PR TITLE
Remove table sets that are no longer used since 93X or earlier

### PR DESCRIPTION
**Pull request by namapane**
Removing the following table sets, that are no longer in use in CMSSW since later releases in the 93X series:
- grid_1103l_071212_3t
- grid_1103l_071212_3_5t
- grid_1103l_071212_3_8t
- grid_120812_3_8t_v7_large
- grid_120812_3_8t_v7_small
- grid_130503_3_8t_v9_large
- grid_130503_3_8t_v9_small
- grid_1103l_090322_3_8t 

Only table sets that are still relevant in CMSSW_11_X are kept unchanged:
- grid_11103l_071212_2t
- grid_11103l_071212_4t
- grid_160812_3t
- grid_160812_3_5t
- grid_160812_3_8t
- grid_160812_3_8t_Run1 

No new file is added.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@cmsbuild, please test
wow thanks @namapane for the cleanup.

**Comment by fabiocos** [comment]
@namapane are all these files obsolete and no more needed anywhere, neither for production nor for test? I assume so, just to be 101% sure

**Comment by namapane** [comment]
Yes, they are obsolete and any cfi using them has been updated (to the best of my knowledge - if any were remaining, they would be a bug to be fixed anyhow).

**Comment by namapane** [comment]
Checking this better: There may still be indirect usage through a deprecated cff in StandardSequences: https://github.com/cms-sw/cmssw/blob/master/Configuration/StandardSequences/python/MagneticField_38T_PostLS1_cff.py
which is deprecated since 2015 - it's time to remove it.
I'm updating all references to this one in the cleanup I am preparing in CMSSW.

**Comment by fabiocos** [comment]
@namapane concerning https://github.com/cms-data/MagneticField-Interpolation/pull/3#issuecomment-545979315 I understand that now this is cleaned in cms-sw/cmssw#28280 , right?

**Comment by namapane** [comment]
@fabiocos, yes correct. It may just take some time for #28280 to be integrated given the number of signatures involved. However none of these .pys is used in automated tests and a good fraction looks obsolete anyhow, so I think there would no problem in proceeding with this PR in parallel in the meanwile, if you wish.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@namapane thanks for this cleaning, I'll try to speed up a bit the integration of cms-sw/cmssw#28280

**Comment by fabiocos** [comment]
@slava77 @perrotta any objection?

**Comment by perrotta** [comment]
+1
- Removal of these tables goes in parallel with the cleaning in #28280
- As noted in https://github.com/cms-sw/cmssw/pull/28280#issuecomment-547950918, perhaps a couple of files more should be cleaned from the reference to the tables removed here: please @namapane have a look

**Comment by namapane** [comment]
> 
> 
> +1
> 
>     * Removal of these tables goes in parallel with the cleaning in #28280
> 
>     * As noted in [cms-sw/cmssw#28280 (comment)](https://github.com/cms-sw/cmssw/pull/28280#issuecomment-547950918), perhaps a couple of files more should be cleaned from the reference to the tables removed here: please @namapane have a look

Tnx @perotta; on your suggestion (for the records): https://github.com/cms-sw/cmssw/pull/28280#issuecomment-548001446

**Comment by slava77** [comment]
@smuzaffar @fabiocos 
is there a reason that this is still open?

**Comment by fabiocos** [comment]
@slava77 no, we were waiting for cms-sw/cmssw#28280 and then I just forgotten about the follow up here. I think it is the right moment to close this request integrating it.

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
cmsdist PR is include this is https://github.com/cms-sw/cmsdist/pull/5404
shoudl be back port it to 11.0.X?

**Comment by slava77** [comment]
this was a cleanup PR. I do not see a need for a backport.

**Comment by fabiocos** [comment]
@slava77 it is not strictly needed, I agree, but it does not harm either and it might leave 11_0_X in a cleaner state

**Pull request merged**
